name: Build XNU Kernel

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build-xnu:
    runs-on: macos-15
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Print runner info
        run: |
          sw_vers
          xcodebuild -version
          uname -a
          sysctl -n hw.ncpu || true

      - name: Install required tools
        run: |
          set -e
          if ! command -v brew >/dev/null 2>&1; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" || true
            echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $GITHUB_ENV
            eval "$(/opt/homebrew/bin/brew shellenv)"
          fi
          brew install autoconf automake libtool gnu-tar || true
          autoconf --version || true

      - name: Download KDK from release
        run: |
          set -e
          curl -L -o kdk.dmg https://github.com/TheRealTechnoGameYT/XNU-Build/releases/download/Rien/kdk.dmg
          hdiutil attach kdk.dmg -nobrowse -quiet -mountpoint /Volumes/_kdk_temp
          sudo mkdir -p /Library/Developer/KDKs
          sudo cp -R /Volumes/_kdk_temp/*.kdk /Library/Developer/KDKs/
          hdiutil detach /Volumes/_kdk_temp -quiet

      - name: Clone XNU sources
        run: |
          git clone --depth 1 https://github.com/apple-oss-distributions/xnu.git xnu-src
          cd xnu-src
          git rev-parse --short HEAD

      - name: Build XNU
        env:
          RC_DARWIN_KERNEL_VERSION: 20
          SDKROOT: ""
        run: |
          cd xnu-src
          ARCH=X86_64
          echo "Building XNU kernel for ARCH=$ARCH"
          make ARCH_CONFIGS=$ARCH KERNEL_CONFIGS=RELEASE -j$(sysctl -n hw.ncpu)

      - name: Upload Kernel Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: xnu-kernel
          path: |
            xnu-src/BUILD/obj/RELEASE_*/kernel
            xnu-src/BUILD/obj/RELEASE_*/*.dSYM
