name: build-xnu

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install gnu-tar make cmake bison flex

      - name: Download KDK
        run: |
          mkdir -p /tmp/kdk
          curl -L -o /tmp/kdk/kdk.tar.gz https://github.com/TheRealTechnoGameYT/XNU-Build/releases/download/Rien/KDK_26.0_25B5042k.kdk.tar.gz
          tar -xzf /tmp/kdk/kdk.tar.gz -C /tmp/kdk
          sudo mkdir -p /Library/Developer/KDKs
          sudo cp -R /tmp/kdk/*.kdk /Library/Developer/KDKs/

      - name: Download XNU source
        run: |
          git clone https://github.com/apple-oss-distributions/xnu.git
          cd xnu
          # Optionnel : checkout sur un tag spécifique
          # git checkout xnu-<version>
          echo "✅ XNU source cloned"

      - name: Build XNU
        run: |
          cd xnu
          make SDKROOT=macosx ARCH_CONFIGS=X86_64 KERNEL_CONFIGS=RELEASE

      - name: Package build
        run: |
          cd xnu/BUILD/obj
          tar -czf xnu-build.tar.gz *
          mv xnu-build.tar.gz $GITHUB_WORKSPACE/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: xnu-build
          path: xnu-build.tar.gz
